<?php

/**
 * @link              https://freshysites.com
 * @since             1.0.0
 * @wordpress-plugin
 * Plugin Name:       Divi Material Icons
 * Description:       Easily load the Google Material Design Icons directly into the Divi Builder. Fo Sho.
 * Version:           1.0.0
 * Author:            FreshySites
 * Author URI:        https://freshysites.com
 * Text Domain:       divi-materialicons-fs
 * Domain Path:       /languages
 */

// If this file is called directly, abort.
if ( ! defined( 'WPINC' ) ) :
	die;
endif;

define( 'FS_DMI_VERSION', '1.0.0' );
define( 'FS_DMI_AUTHOR', 'FreshySites' );
define( 'FS_DMI_OPTIONS_NAME', 'divi_materialicons_fs_settings' );
define( 'FS_DMI_PLUGIN_SLUG', 'divi-materialicons-fs' );
define( 'FS_DMI_STORE_URL', 'https://elegantmarketplace.com' );
define( 'FS_DMI_ITEM_NAME', 'Divi Material Icons' );
define( 'FS_DMI_SETTINGS', 'divi_materialicons_fs_settings' );

/**
 * Filter plugin action links.
 *
 * @since    1.0.0
 */
function fs_dmi_add_action_plugin( $actions, $plugin_file ) {
	static $plugin;

	if ( ! isset( $plugin ) )
		$plugin = plugin_basename(__FILE__);
	
	if ($plugin == $plugin_file) :

		$settings = array('settings' => '<a href="options-general.php?page=' . FS_DMI_SETTINGS . '">' . __('Settings', 'General') . '</a>');
		//$site_link = array('support' => '<a href="https://freshysites.com" target="_blank">Support</a>');
		
    	$actions = array_merge($settings, $actions);
		//$actions = array_merge($site_link, $actions);
			
	endif;
		
	return $actions;
}

/**
 * Register the admin menu.
 *
 * @since    1.0.0
 */
function fs_dmi_admin_menu() {
	add_submenu_page(
		'options-general.php',	// parent slug
		'Divi Material Icons',	// page title
		'Divi Material Icons',	// menu title
		'manage_options',		//capability
		FS_DMI_SETTINGS,		// slug
		'fs_dmi_settings_page'  // callback 
	);
}

function fs_dmi_settings_page() { ?>

	<div class="wrap">
		<h1><?php echo esc_html( get_admin_page_title() ); ?></h1>
		<div id="poststuff">
			<div id="post-body" class="metabox-holder columns-2">
				<div class="fs_dmi_settings">
					<p>You're ready to use Google's Material Design Icons 
					directly in your Divi Builder! This plugin uses the Google Fonts API, which is the 
					<a href="https://google.github.io/material-design-icons/#setup-method-1-using-via-google-web-fonts" target="_blank">recommended method</a> 
					of implementation. It's served up directly from Google Web Fonts &mdash; quickly and reliably.</p>

					<p>Here's a <a href="https://www.google.com/design/icons/" target="_blank">cheat sheet</a> for you</p>
				</div>
				<p class="fs_dmi_credits">Built with <span class="dashicons dashicons-heart"></span> by Jon Fuller at FreshySites. Cheers!</p>
				<p class="fs_dmi_credits">Please note, we can not provide full support for this plugin. But please <a href="mailto:jon@freshysites.com?subject=Divi%20Material%20Icons%20Plugin">email me</a> if you run into trouble.</p>
			</div>
		</div>
	</div>
	<?php
}

function fs_dmi_materialicons() {
	wp_enqueue_style( FS_DMI_PLUGIN_SLUG, 'https://fonts.googleapis.com/icon?family=Material+Icons', array(), FS_DMI_VERSION, 'all' );
	// Load our custom stylesheet
	wp_enqueue_style( FS_DMI_PLUGIN_SLUG . '-custom',  plugin_dir_url( __FILE__ ) . 'assets/' . FS_DMI_PLUGIN_SLUG . '.css', array(), FS_DMI_VERSION, 'all' );
}

function fs_dmi_public_script() {
	wp_enqueue_script( FS_DMI_PLUGIN_SLUG . '-custom',  plugin_dir_url( __FILE__ ) . 'assets/' . FS_DMI_PLUGIN_SLUG . '.js', array('jquery'), FS_DMI_VERSION, true );
}

/**
 * Add Material Icons icons to Divi.
 *
 * @since    1.0.0
 */
function materialicons_icons( $icons ) {
	
	$material_icons = array(
'mi-&#xe84d;', /* 3d_rotation */
'mi-&#xeb3b;', /* ac_unit */
'mi-&#xe190;', /* access_alarm */
'mi-&#xe191;', /* access_alarms */
'mi-&#xe192;', /* access_time */
'mi-&#xe84e;', /* accessibility */
'mi-&#xe914;', /* accessible */
'mi-&#xe84f;', /* account_balance */
'mi-&#xe850;', /* account_balance_wallet */
'mi-&#xe851;', /* account_box */
'mi-&#xe853;', /* account_circle */
'mi-&#xe60e;', /* adb */
'mi-&#xe145;', /* add */
'mi-&#xe439;', /* add_a_photo */
'mi-&#xe193;', /* add_alarm */
'mi-&#xe003;', /* add_alert */
'mi-&#xe146;', /* add_box */
'mi-&#xe147;', /* add_circle */
'mi-&#xe148;', /* add_circle_outline */
'mi-&#xe567;', /* add_location */
'mi-&#xe854;', /* add_shopping_cart */
'mi-&#xe39d;', /* add_to_photos */
'mi-&#xe05c;', /* add_to_queue */
'mi-&#xe39e;', /* adjust */
'mi-&#xe630;', /* airline_seat_flat */
'mi-&#xe631;', /* airline_seat_flat_angled */
'mi-&#xe632;', /* airline_seat_individual_suite */
'mi-&#xe633;', /* airline_seat_legroom_extra */
'mi-&#xe634;', /* airline_seat_legroom_normal */
'mi-&#xe635;', /* airline_seat_legroom_reduced */
'mi-&#xe636;', /* airline_seat_recline_extra */
'mi-&#xe637;', /* airline_seat_recline_normal */
'mi-&#xe195;', /* airplanemode_active */
'mi-&#xe194;', /* airplanemode_inactive */
'mi-&#xe055;', /* airplay */
'mi-&#xeb3c;', /* airport_shuttle */
'mi-&#xe855;', /* alarm */
'mi-&#xe856;', /* alarm_add */
'mi-&#xe857;', /* alarm_off */
'mi-&#xe858;', /* alarm_on */
'mi-&#xe019;', /* album */
'mi-&#xeb3d;', /* all_inclusive */
'mi-&#xe90b;', /* all_out */
'mi-&#xe859;', /* android */
'mi-&#xe85a;', /* announcement */
'mi-&#xe5c3;', /* apps */
'mi-&#xe149;', /* archive */
'mi-&#xe5c4;', /* arrow_back */
'mi-&#xe5db;', /* arrow_downward */
'mi-&#xe5c5;', /* arrow_drop_down */
'mi-&#xe5c6;', /* arrow_drop_down_circle */
'mi-&#xe5c7;', /* arrow_drop_up */
'mi-&#xe5c8;', /* arrow_forward */
'mi-&#xe5d8;', /* arrow_upward */
'mi-&#xe060;', /* art_track */
'mi-&#xe85b;', /* aspect_ratio */
'mi-&#xe85c;', /* assessment */
'mi-&#xe85d;', /* assignment */
'mi-&#xe85e;', /* assignment_ind */
'mi-&#xe85f;', /* assignment_late */
'mi-&#xe860;', /* assignment_return */
'mi-&#xe861;', /* assignment_returned */
'mi-&#xe862;', /* assignment_turned_in */
'mi-&#xe39f;', /* assistant */
'mi-&#xe3a0;', /* assistant_photo */
'mi-&#xe226;', /* attach_file */
'mi-&#xe227;', /* attach_money */
'mi-&#xe2bc;', /* attachment */
'mi-&#xe3a1;', /* audiotrack */
'mi-&#xe863;', /* autorenew */
'mi-&#xe01b;', /* av_timer */
'mi-&#xe14a;', /* backspace */
'mi-&#xe864;', /* backup */
'mi-&#xe19c;', /* battery_alert */
'mi-&#xe1a3;', /* battery_charging_full */
'mi-&#xe1a4;', /* battery_full */
'mi-&#xe1a5;', /* battery_std */
'mi-&#xe1a6;', /* battery_unknown */
'mi-&#xeb3e;', /* beach_access */
'mi-&#xe52d;', /* beenhere */
'mi-&#xe14b;', /* block */
'mi-&#xe1a7;', /* bluetooth */
'mi-&#xe60f;', /* bluetooth_audio */
'mi-&#xe1a8;', /* bluetooth_connected */
'mi-&#xe1a9;', /* bluetooth_disabled */
'mi-&#xe1aa;', /* bluetooth_searching */
'mi-&#xe3a2;', /* blur_circular */
'mi-&#xe3a3;', /* blur_linear */
'mi-&#xe3a4;', /* blur_off */
'mi-&#xe3a5;', /* blur_on */
'mi-&#xe865;', /* book */
'mi-&#xe866;', /* bookmark */
'mi-&#xe867;', /* bookmark_border */
'mi-&#xe228;', /* border_all */
'mi-&#xe229;', /* border_bottom */
'mi-&#xe22a;', /* border_clear */
'mi-&#xe22b;', /* border_color */
'mi-&#xe22c;', /* border_horizontal */
'mi-&#xe22d;', /* border_inner */
'mi-&#xe22e;', /* border_left */
'mi-&#xe22f;', /* border_outer */
'mi-&#xe230;', /* border_right */
'mi-&#xe231;', /* border_style */
'mi-&#xe232;', /* border_top */
'mi-&#xe233;', /* border_vertical */
'mi-&#xe06b;', /* branding_watermark */
'mi-&#xe3a6;', /* brightness_1 */
'mi-&#xe3a7;', /* brightness_2 */
'mi-&#xe3a8;', /* brightness_3 */
'mi-&#xe3a9;', /* brightness_4 */
'mi-&#xe3aa;', /* brightness_5 */
'mi-&#xe3ab;', /* brightness_6 */
'mi-&#xe3ac;', /* brightness_7 */
'mi-&#xe1ab;', /* brightness_auto */
'mi-&#xe1ac;', /* brightness_high */
'mi-&#xe1ad;', /* brightness_low */
'mi-&#xe1ae;', /* brightness_medium */
'mi-&#xe3ad;', /* broken_image */
'mi-&#xe3ae;', /* brush */
'mi-&#xe6dd;', /* bubble_chart */
'mi-&#xe868;', /* bug_report */
'mi-&#xe869;', /* build */
'mi-&#xe43c;', /* burst_mode */
'mi-&#xe0af;', /* business */
'mi-&#xeb3f;', /* business_center */
'mi-&#xe86a;', /* cached */
'mi-&#xe7e9;', /* cake */
'mi-&#xe0b0;', /* call */
'mi-&#xe0b1;', /* call_end */
'mi-&#xe0b2;', /* call_made */
'mi-&#xe0b3;', /* call_merge */
'mi-&#xe0b4;', /* call_missed */
'mi-&#xe0e4;', /* call_missed_outgoing */
'mi-&#xe0b5;', /* call_received */
'mi-&#xe0b6;', /* call_split */
'mi-&#xe06c;', /* call_to_action */
'mi-&#xe3af;', /* camera */
'mi-&#xe3b0;', /* camera_alt */
'mi-&#xe8fc;', /* camera_enhance */
'mi-&#xe3b1;', /* camera_front */
'mi-&#xe3b2;', /* camera_rear */
'mi-&#xe3b3;', /* camera_roll */
'mi-&#xe5c9;', /* cancel */
'mi-&#xe8f6;', /* card_giftcard */
'mi-&#xe8f7;', /* card_membership */
'mi-&#xe8f8;', /* card_travel */
'mi-&#xeb40;', /* casino */
'mi-&#xe307;', /* cast */
'mi-&#xe308;', /* cast_connected */
'mi-&#xe3b4;', /* center_focus_strong */
'mi-&#xe3b5;', /* center_focus_weak */
'mi-&#xe86b;', /* change_history */
'mi-&#xe0b7;', /* chat */
'mi-&#xe0ca;', /* chat_bubble */
'mi-&#xe0cb;', /* chat_bubble_outline */
'mi-&#xe5ca;', /* check */
'mi-&#xe834;', /* check_box */
'mi-&#xe835;', /* check_box_outline_blank */
'mi-&#xe86c;', /* check_circle */
'mi-&#xe5cb;', /* chevron_left */
'mi-&#xe5cc;', /* chevron_right */
'mi-&#xeb41;', /* child_care */
'mi-&#xeb42;', /* child_friendly */
'mi-&#xe86d;', /* chrome_reader_mode */
'mi-&#xe86e;', /* class */
'mi-&#xe14c;', /* clear */
'mi-&#xe0b8;', /* clear_all */
'mi-&#xe5cd;', /* close */
'mi-&#xe01c;', /* closed_caption */
'mi-&#xe2bd;', /* cloud */
'mi-&#xe2be;', /* cloud_circle */
'mi-&#xe2bf;', /* cloud_done */
'mi-&#xe2c0;', /* cloud_download */
'mi-&#xe2c1;', /* cloud_off */
'mi-&#xe2c2;', /* cloud_queue */
'mi-&#xe2c3;', /* cloud_upload */
'mi-&#xe86f;', /* code */
'mi-&#xe3b6;', /* collections */
'mi-&#xe431;', /* collections_bookmark */
'mi-&#xe3b7;', /* color_lens */
'mi-&#xe3b8;', /* colorize */
'mi-&#xe0b9;', /* comment */
'mi-&#xe3b9;', /* compare */
'mi-&#xe915;', /* compare_arrows */
'mi-&#xe30a;', /* computer */
'mi-&#xe638;', /* confirmation_number */
'mi-&#xe0d0;', /* contact_mail */
'mi-&#xe0cf;', /* contact_phone */
'mi-&#xe0ba;', /* contacts */
'mi-&#xe14d;', /* content_copy */
'mi-&#xe14e;', /* content_cut */
'mi-&#xe14f;', /* content_paste */
'mi-&#xe3ba;', /* control_point */
'mi-&#xe3bb;', /* control_point_duplicate */
'mi-&#xe90c;', /* copyright */
'mi-&#xe150;', /* create */
'mi-&#xe2cc;', /* create_new_folder */
'mi-&#xe870;', /* credit_card */
'mi-&#xe3be;', /* crop */
'mi-&#xe3bc;', /* crop_16_9 */
'mi-&#xe3bd;', /* crop_3_2 */
'mi-&#xe3bf;', /* crop_5_4 */
'mi-&#xe3c0;', /* crop_7_5 */
'mi-&#xe3c1;', /* crop_din */
'mi-&#xe3c2;', /* crop_free */
'mi-&#xe3c3;', /* crop_landscape */
'mi-&#xe3c4;', /* crop_original */
'mi-&#xe3c5;', /* crop_portrait */
'mi-&#xe437;', /* crop_rotate */
'mi-&#xe3c6;', /* crop_square */
'mi-&#xe871;', /* dashboard */
'mi-&#xe1af;', /* data_usage */
'mi-&#xe916;', /* date_range */
'mi-&#xe3c7;', /* dehaze */
'mi-&#xe872;', /* delete */
'mi-&#xe92b;', /* delete_forever */
'mi-&#xe16c;', /* delete_sweep */
'mi-&#xe873;', /* description */
'mi-&#xe30b;', /* desktop_mac */
'mi-&#xe30c;', /* desktop_windows */
'mi-&#xe3c8;', /* details */
'mi-&#xe30d;', /* developer_board */
'mi-&#xe1b0;', /* developer_mode */
'mi-&#xe335;', /* device_hub */
'mi-&#xe1b1;', /* devices */
'mi-&#xe337;', /* devices_other */
'mi-&#xe0bb;', /* dialer_sip */
'mi-&#xe0bc;', /* dialpad */
'mi-&#xe52e;', /* directions */
'mi-&#xe52f;', /* directions_bike */
'mi-&#xe532;', /* directions_boat */
'mi-&#xe530;', /* directions_bus */
'mi-&#xe531;', /* directions_car */
'mi-&#xe534;', /* directions_railway */
'mi-&#xe566;', /* directions_run */
'mi-&#xe533;', /* directions_subway */
'mi-&#xe535;', /* directions_transit */
'mi-&#xe536;', /* directions_walk */
'mi-&#xe610;', /* disc_full */
'mi-&#xe875;', /* dns */
'mi-&#xe612;', /* do_not_disturb */
'mi-&#xe611;', /* do_not_disturb_alt */
'mi-&#xe643;', /* do_not_disturb_off */
'mi-&#xe644;', /* do_not_disturb_on */
'mi-&#xe30e;', /* dock */
'mi-&#xe7ee;', /* domain */
'mi-&#xe876;', /* done */
'mi-&#xe877;', /* done_all */
'mi-&#xe917;', /* donut_large */
'mi-&#xe918;', /* donut_small */
'mi-&#xe151;', /* drafts */
'mi-&#xe25d;', /* drag_handle */
'mi-&#xe613;', /* drive_eta */
'mi-&#xe1b2;', /* dvr */
'mi-&#xe3c9;', /* edit */
'mi-&#xe568;', /* edit_location */
'mi-&#xe8fb;', /* eject */
'mi-&#xe0be;', /* email */
'mi-&#xe63f;', /* enhanced_encryption */
'mi-&#xe01d;', /* equalizer */
'mi-&#xe000;', /* error */
'mi-&#xe001;', /* error_outline */
'mi-&#xe926;', /* euro_symbol */
'mi-&#xe56d;', /* ev_station */
'mi-&#xe878;', /* event */
'mi-&#xe614;', /* event_available */
'mi-&#xe615;', /* event_busy */
'mi-&#xe616;', /* event_note */
'mi-&#xe903;', /* event_seat */
'mi-&#xe879;', /* exit_to_app */
'mi-&#xe5ce;', /* expand_less */
'mi-&#xe5cf;', /* expand_more */
'mi-&#xe01e;', /* explicit */
'mi-&#xe87a;', /* explore */
'mi-&#xe3ca;', /* exposure */
'mi-&#xe3cb;', /* exposure_neg_1 */
'mi-&#xe3cc;', /* exposure_neg_2 */
'mi-&#xe3cd;', /* exposure_plus_1 */
'mi-&#xe3ce;', /* exposure_plus_2 */
'mi-&#xe3cf;', /* exposure_zero */
'mi-&#xe87b;', /* extension */
'mi-&#xe87c;', /* face */
'mi-&#xe01f;', /* fast_forward */
'mi-&#xe020;', /* fast_rewind */
'mi-&#xe87d;', /* favorite */
'mi-&#xe87e;', /* favorite_border */
'mi-&#xe06d;', /* featured_play_list */
'mi-&#xe06e;', /* featured_video */
'mi-&#xe87f;', /* feedback */
'mi-&#xe05d;', /* fiber_dvr */
'mi-&#xe061;', /* fiber_manual_record */
'mi-&#xe05e;', /* fiber_new */
'mi-&#xe06a;', /* fiber_pin */
'mi-&#xe062;', /* fiber_smart_record */
'mi-&#xe2c4;', /* file_download */
'mi-&#xe2c6;', /* file_upload */
'mi-&#xe3d3;', /* filter */
'mi-&#xe3d0;', /* filter_1 */
'mi-&#xe3d1;', /* filter_2 */
'mi-&#xe3d2;', /* filter_3 */
'mi-&#xe3d4;', /* filter_4 */
'mi-&#xe3d5;', /* filter_5 */
'mi-&#xe3d6;', /* filter_6 */
'mi-&#xe3d7;', /* filter_7 */
'mi-&#xe3d8;', /* filter_8 */
'mi-&#xe3d9;', /* filter_9 */
'mi-&#xe3da;', /* filter_9_plus */
'mi-&#xe3db;', /* filter_b_and_w */
'mi-&#xe3dc;', /* filter_center_focus */
'mi-&#xe3dd;', /* filter_drama */
'mi-&#xe3de;', /* filter_frames */
'mi-&#xe3df;', /* filter_hdr */
'mi-&#xe152;', /* filter_list */
'mi-&#xe3e0;', /* filter_none */
'mi-&#xe3e2;', /* filter_tilt_shift */
'mi-&#xe3e3;', /* filter_vintage */
'mi-&#xe880;', /* find_in_page */
'mi-&#xe881;', /* find_replace */
'mi-&#xe90d;', /* fingerprint */
'mi-&#xe5dc;', /* first_page */
'mi-&#xeb43;', /* fitness_center */
'mi-&#xe153;', /* flag */
'mi-&#xe3e4;', /* flare */
'mi-&#xe3e5;', /* flash_auto */
'mi-&#xe3e6;', /* flash_off */
'mi-&#xe3e7;', /* flash_on */
'mi-&#xe539;', /* flight */
'mi-&#xe904;', /* flight_land */
'mi-&#xe905;', /* flight_takeoff */
'mi-&#xe3e8;', /* flip */
'mi-&#xe882;', /* flip_to_back */
'mi-&#xe883;', /* flip_to_front */
'mi-&#xe2c7;', /* folder */
'mi-&#xe2c8;', /* folder_open */
'mi-&#xe2c9;', /* folder_shared */
'mi-&#xe617;', /* folder_special */
'mi-&#xe167;', /* font_download */
'mi-&#xe234;', /* format_align_center */
'mi-&#xe235;', /* format_align_justify */
'mi-&#xe236;', /* format_align_left */
'mi-&#xe237;', /* format_align_right */
'mi-&#xe238;', /* format_bold */
'mi-&#xe239;', /* format_clear */
'mi-&#xe23a;', /* format_color_fill */
'mi-&#xe23b;', /* format_color_reset */
'mi-&#xe23c;', /* format_color_text */
'mi-&#xe23d;', /* format_indent_decrease */
'mi-&#xe23e;', /* format_indent_increase */
'mi-&#xe23f;', /* format_italic */
'mi-&#xe240;', /* format_line_spacing */
'mi-&#xe241;', /* format_list_bulleted */
'mi-&#xe242;', /* format_list_numbered */
'mi-&#xe243;', /* format_paint */
'mi-&#xe244;', /* format_quote */
'mi-&#xe25e;', /* format_shapes */
'mi-&#xe245;', /* format_size */
'mi-&#xe246;', /* format_strikethrough */
'mi-&#xe247;', /* format_textdirection_l_to_r */
'mi-&#xe248;', /* format_textdirection_r_to_l */
'mi-&#xe249;', /* format_underlined */
'mi-&#xe0bf;', /* forum */
'mi-&#xe154;', /* forward */
'mi-&#xe056;', /* forward_10 */
'mi-&#xe057;', /* forward_30 */
'mi-&#xe058;', /* forward_5 */
'mi-&#xeb44;', /* free_breakfast */
'mi-&#xe5d0;', /* fullscreen */
'mi-&#xe5d1;', /* fullscreen_exit */
'mi-&#xe24a;', /* functions */
'mi-&#xe927;', /* g_translate */
'mi-&#xe30f;', /* gamepad */
'mi-&#xe021;', /* games */
'mi-&#xe90e;', /* gavel */
'mi-&#xe155;', /* gesture */
'mi-&#xe884;', /* get_app */
'mi-&#xe908;', /* gif */
'mi-&#xeb45;', /* golf_course */
'mi-&#xe1b3;', /* gps_fixed */
'mi-&#xe1b4;', /* gps_not_fixed */
'mi-&#xe1b5;', /* gps_off */
'mi-&#xe885;', /* grade */
'mi-&#xe3e9;', /* gradient */
'mi-&#xe3ea;', /* grain */
'mi-&#xe1b8;', /* graphic_eq */
'mi-&#xe3eb;', /* grid_off */
'mi-&#xe3ec;', /* grid_on */
'mi-&#xe7ef;', /* group */
'mi-&#xe7f0;', /* group_add */
'mi-&#xe886;', /* group_work */
'mi-&#xe052;', /* hd */
'mi-&#xe3ed;', /* hdr_off */
'mi-&#xe3ee;', /* hdr_on */
'mi-&#xe3f1;', /* hdr_strong */
'mi-&#xe3f2;', /* hdr_weak */
'mi-&#xe310;', /* headset */
'mi-&#xe311;', /* headset_mic */
'mi-&#xe3f3;', /* healing */
'mi-&#xe023;', /* hearing */
'mi-&#xe887;', /* help */
'mi-&#xe8fd;', /* help_outline */
'mi-&#xe024;', /* high_quality */
'mi-&#xe25f;', /* highlight */
'mi-&#xe888;', /* highlight_off */
'mi-&#xe889;', /* history */
'mi-&#xe88a;', /* home */
'mi-&#xeb46;', /* hot_tub */
'mi-&#xe53a;', /* hotel */
'mi-&#xe88b;', /* hourglass_empty */
'mi-&#xe88c;', /* hourglass_full */
'mi-&#xe902;', /* http */
'mi-&#xe88d;', /* https */
'mi-&#xe3f4;', /* image */
'mi-&#xe3f5;', /* image_aspect_ratio */
'mi-&#xe0e0;', /* import_contacts */
'mi-&#xe0c3;', /* import_export */
'mi-&#xe912;', /* important_devices */
'mi-&#xe156;', /* inbox */
'mi-&#xe909;', /* indeterminate_check_box */
'mi-&#xe88e;', /* info */
'mi-&#xe88f;', /* info_outline */
'mi-&#xe890;', /* input */
'mi-&#xe24b;', /* insert_chart */
'mi-&#xe24c;', /* insert_comment */
'mi-&#xe24d;', /* insert_drive_file */
'mi-&#xe24e;', /* insert_emoticon */
'mi-&#xe24f;', /* insert_invitation */
'mi-&#xe250;', /* insert_link */
'mi-&#xe251;', /* insert_photo */
'mi-&#xe891;', /* invert_colors */
'mi-&#xe0c4;', /* invert_colors_off */
'mi-&#xe3f6;', /* iso */
'mi-&#xe312;', /* keyboard */
'mi-&#xe313;', /* keyboard_arrow_down */
'mi-&#xe314;', /* keyboard_arrow_left */
'mi-&#xe315;', /* keyboard_arrow_right */
'mi-&#xe316;', /* keyboard_arrow_up */
'mi-&#xe317;', /* keyboard_backspace */
'mi-&#xe318;', /* keyboard_capslock */
'mi-&#xe31a;', /* keyboard_hide */
'mi-&#xe31b;', /* keyboard_return */
'mi-&#xe31c;', /* keyboard_tab */
'mi-&#xe31d;', /* keyboard_voice */
'mi-&#xeb47;', /* kitchen */
'mi-&#xe892;', /* label */
'mi-&#xe893;', /* label_outline */
'mi-&#xe3f7;', /* landscape */
'mi-&#xe894;', /* language */
'mi-&#xe31e;', /* laptop */
'mi-&#xe31f;', /* laptop_chromebook */
'mi-&#xe320;', /* laptop_mac */
'mi-&#xe321;', /* laptop_windows */
'mi-&#xe5dd;', /* last_page */
'mi-&#xe895;', /* launch */
'mi-&#xe53b;', /* layers */
'mi-&#xe53c;', /* layers_clear */
'mi-&#xe3f8;', /* leak_add */
'mi-&#xe3f9;', /* leak_remove */
'mi-&#xe3fa;', /* lens */
'mi-&#xe02e;', /* library_add */
'mi-&#xe02f;', /* library_books */
'mi-&#xe030;', /* library_music */
'mi-&#xe90f;', /* lightbulb_outline */
'mi-&#xe919;', /* line_style */
'mi-&#xe91a;', /* line_weight */
'mi-&#xe260;', /* linear_scale */
'mi-&#xe157;', /* link */
'mi-&#xe438;', /* linked_camera */
'mi-&#xe896;', /* list */
'mi-&#xe0c6;', /* live_help */
'mi-&#xe639;', /* live_tv */
'mi-&#xe53f;', /* local_activity */
'mi-&#xe53d;', /* local_airport */
'mi-&#xe53e;', /* local_atm */
'mi-&#xe540;', /* local_bar */
'mi-&#xe541;', /* local_cafe */
'mi-&#xe542;', /* local_car_wash */
'mi-&#xe543;', /* local_convenience_store */
'mi-&#xe556;', /* local_dining */
'mi-&#xe544;', /* local_drink */
'mi-&#xe545;', /* local_florist */
'mi-&#xe546;', /* local_gas_station */
'mi-&#xe547;', /* local_grocery_store */
'mi-&#xe548;', /* local_hospital */
'mi-&#xe549;', /* local_hotel */
'mi-&#xe54a;', /* local_laundry_service */
'mi-&#xe54b;', /* local_library */
'mi-&#xe54c;', /* local_mall */
'mi-&#xe54d;', /* local_movies */
'mi-&#xe54e;', /* local_offer */
'mi-&#xe54f;', /* local_parking */
'mi-&#xe550;', /* local_pharmacy */
'mi-&#xe551;', /* local_phone */
'mi-&#xe552;', /* local_pizza */
'mi-&#xe553;', /* local_play */
'mi-&#xe554;', /* local_post_office */
'mi-&#xe555;', /* local_printshop */
'mi-&#xe557;', /* local_see */
'mi-&#xe558;', /* local_shipping */
'mi-&#xe559;', /* local_taxi */
'mi-&#xe7f1;', /* location_city */
'mi-&#xe1b6;', /* location_disabled */
'mi-&#xe0c7;', /* location_off */
'mi-&#xe0c8;', /* location_on */
'mi-&#xe1b7;', /* location_searching */
'mi-&#xe897;', /* lock */
'mi-&#xe898;', /* lock_open */
'mi-&#xe899;', /* lock_outline */
'mi-&#xe3fc;', /* looks */
'mi-&#xe3fb;', /* looks_3 */
'mi-&#xe3fd;', /* looks_4 */
'mi-&#xe3fe;', /* looks_5 */
'mi-&#xe3ff;', /* looks_6 */
'mi-&#xe400;', /* looks_one */
'mi-&#xe401;', /* looks_two */
'mi-&#xe028;', /* loop */
'mi-&#xe402;', /* loupe */
'mi-&#xe16d;', /* low_priority */
'mi-&#xe89a;', /* loyalty */
'mi-&#xe158;', /* mail */
'mi-&#xe0e1;', /* mail_outline */
'mi-&#xe55b;', /* map */
'mi-&#xe159;', /* markunread */
'mi-&#xe89b;', /* markunread_mailbox */
'mi-&#xe322;', /* memory */
'mi-&#xe5d2;', /* menu */
'mi-&#xe252;', /* merge_type */
'mi-&#xe0c9;', /* message */
'mi-&#xe029;', /* mic */
'mi-&#xe02a;', /* mic_none */
'mi-&#xe02b;', /* mic_off */
'mi-&#xe618;', /* mms */
'mi-&#xe253;', /* mode_comment */
'mi-&#xe254;', /* mode_edit */
'mi-&#xe263;', /* monetization_on */
'mi-&#xe25c;', /* money_off */
'mi-&#xe403;', /* monochrome_photos */
'mi-&#xe7f2;', /* mood */
'mi-&#xe7f3;', /* mood_bad */
'mi-&#xe619;', /* more */
'mi-&#xe5d3;', /* more_horiz */
'mi-&#xe5d4;', /* more_vert */
'mi-&#xe91b;', /* motorcycle */
'mi-&#xe323;', /* mouse */
'mi-&#xe168;', /* move_to_inbox */
'mi-&#xe02c;', /* movie */
'mi-&#xe404;', /* movie_creation */
'mi-&#xe43a;', /* movie_filter */
'mi-&#xe6df;', /* multiline_chart */
'mi-&#xe405;', /* music_note */
'mi-&#xe063;', /* music_video */
'mi-&#xe55c;', /* my_location */
'mi-&#xe406;', /* nature */
'mi-&#xe407;', /* nature_people */
'mi-&#xe408;', /* navigate_before */
'mi-&#xe409;', /* navigate_next */
'mi-&#xe55d;', /* navigation */
'mi-&#xe569;', /* near_me */
'mi-&#xe1b9;', /* network_cell */
'mi-&#xe640;', /* network_check */
'mi-&#xe61a;', /* network_locked */
'mi-&#xe1ba;', /* network_wifi */
'mi-&#xe031;', /* new_releases */
'mi-&#xe16a;', /* next_week */
'mi-&#xe1bb;', /* nfc */
'mi-&#xe641;', /* no_encryption */
'mi-&#xe0cc;', /* no_sim */
'mi-&#xe033;', /* not_interested */
'mi-&#xe06f;', /* note */
'mi-&#xe89c;', /* note_add */
'mi-&#xe7f4;', /* notifications */
'mi-&#xe7f7;', /* notifications_active */
'mi-&#xe7f5;', /* notifications_none */
'mi-&#xe7f6;', /* notifications_off */
'mi-&#xe7f8;', /* notifications_paused */
'mi-&#xe90a;', /* offline_pin */
'mi-&#xe63a;', /* ondemand_video */
'mi-&#xe91c;', /* opacity */
'mi-&#xe89d;', /* open_in_browser */
'mi-&#xe89e;', /* open_in_new */
'mi-&#xe89f;', /* open_with */
'mi-&#xe7f9;', /* pages */
'mi-&#xe8a0;', /* pageview */
'mi-&#xe40a;', /* palette */
'mi-&#xe925;', /* pan_tool */
'mi-&#xe40b;', /* panorama */
'mi-&#xe40c;', /* panorama_fish_eye */
'mi-&#xe40d;', /* panorama_horizontal */
'mi-&#xe40e;', /* panorama_vertical */
'mi-&#xe40f;', /* panorama_wide_angle */
'mi-&#xe7fa;', /* party_mode */
'mi-&#xe034;', /* pause */
'mi-&#xe035;', /* pause_circle_filled */
'mi-&#xe036;', /* pause_circle_outline */
'mi-&#xe8a1;', /* payment */
'mi-&#xe7fb;', /* people */
'mi-&#xe7fc;', /* people_outline */
'mi-&#xe8a2;', /* perm_camera_mic */
'mi-&#xe8a3;', /* perm_contact_calendar */
'mi-&#xe8a4;', /* perm_data_setting */
'mi-&#xe8a5;', /* perm_device_information */
'mi-&#xe8a6;', /* perm_identity */
'mi-&#xe8a7;', /* perm_media */
'mi-&#xe8a8;', /* perm_phone_msg */
'mi-&#xe8a9;', /* perm_scan_wifi */
'mi-&#xe7fd;', /* person */
'mi-&#xe7fe;', /* person_add */
'mi-&#xe7ff;', /* person_outline */
'mi-&#xe55a;', /* person_pin */
'mi-&#xe56a;', /* person_pin_circle */
'mi-&#xe63b;', /* personal_video */
'mi-&#xe91d;', /* pets */
'mi-&#xe0cd;', /* phone */
'mi-&#xe324;', /* phone_android */
'mi-&#xe61b;', /* phone_bluetooth_speaker */
'mi-&#xe61c;', /* phone_forwarded */
'mi-&#xe61d;', /* phone_in_talk */
'mi-&#xe325;', /* phone_iphone */
'mi-&#xe61e;', /* phone_locked */
'mi-&#xe61f;', /* phone_missed */
'mi-&#xe620;', /* phone_paused */
'mi-&#xe326;', /* phonelink */
'mi-&#xe0db;', /* phonelink_erase */
'mi-&#xe0dc;', /* phonelink_lock */
'mi-&#xe327;', /* phonelink_off */
'mi-&#xe0dd;', /* phonelink_ring */
'mi-&#xe0de;', /* phonelink_setup */
'mi-&#xe410;', /* photo */
'mi-&#xe411;', /* photo_album */
'mi-&#xe412;', /* photo_camera */
'mi-&#xe43b;', /* photo_filter */
'mi-&#xe413;', /* photo_library */
'mi-&#xe432;', /* photo_size_select_actual */
'mi-&#xe433;', /* photo_size_select_large */
'mi-&#xe434;', /* photo_size_select_small */
'mi-&#xe415;', /* picture_as_pdf */
'mi-&#xe8aa;', /* picture_in_picture */
'mi-&#xe911;', /* picture_in_picture_alt */
'mi-&#xe6c4;', /* pie_chart */
'mi-&#xe6c5;', /* pie_chart_outlined */
'mi-&#xe55e;', /* pin_drop */
'mi-&#xe55f;', /* place */
'mi-&#xe037;', /* play_arrow */
'mi-&#xe038;', /* play_circle_filled */
'mi-&#xe039;', /* play_circle_outline */
'mi-&#xe906;', /* play_for_work */
'mi-&#xe03b;', /* playlist_add */
'mi-&#xe065;', /* playlist_add_check */
'mi-&#xe05f;', /* playlist_play */
'mi-&#xe800;', /* plus_one */
'mi-&#xe801;', /* poll */
'mi-&#xe8ab;', /* polymer */
'mi-&#xeb48;', /* pool */
'mi-&#xe0ce;', /* portable_wifi_off */
'mi-&#xe416;', /* portrait */
'mi-&#xe63c;', /* power */
'mi-&#xe336;', /* power_input */
'mi-&#xe8ac;', /* power_settings_new */
'mi-&#xe91e;', /* pregnant_woman */
'mi-&#xe0df;', /* present_to_all */
'mi-&#xe8ad;', /* print */
'mi-&#xe645;', /* priority_high */
'mi-&#xe80b;', /* public */
'mi-&#xe255;', /* publish */
'mi-&#xe8ae;', /* query_builder */
'mi-&#xe8af;', /* question_answer */
'mi-&#xe03c;', /* queue */
'mi-&#xe03d;', /* queue_music */
'mi-&#xe066;', /* queue_play_next */
'mi-&#xe03e;', /* radio */
'mi-&#xe837;', /* radio_button_checked */
'mi-&#xe836;', /* radio_button_unchecked */
'mi-&#xe560;', /* rate_review */
'mi-&#xe8b0;', /* receipt */
'mi-&#xe03f;', /* recent_actors */
'mi-&#xe91f;', /* record_voice_over */
'mi-&#xe8b1;', /* redeem */
'mi-&#xe15a;', /* redo */
'mi-&#xe5d5;', /* refresh */
'mi-&#xe15b;', /* remove */
'mi-&#xe15c;', /* remove_circle */
'mi-&#xe15d;', /* remove_circle_outline */
'mi-&#xe067;', /* remove_from_queue */
'mi-&#xe417;', /* remove_red_eye */
'mi-&#xe928;', /* remove_shopping_cart */
'mi-&#xe8fe;', /* reorder */
'mi-&#xe040;', /* repeat */
'mi-&#xe041;', /* repeat_one */
'mi-&#xe042;', /* replay */
'mi-&#xe059;', /* replay_10 */
'mi-&#xe05a;', /* replay_30 */
'mi-&#xe05b;', /* replay_5 */
'mi-&#xe15e;', /* reply */
'mi-&#xe15f;', /* reply_all */
'mi-&#xe160;', /* report */
'mi-&#xe8b2;', /* report_problem */
'mi-&#xe56c;', /* restaurant */
'mi-&#xe561;', /* restaurant_menu */
'mi-&#xe8b3;', /* restore */
'mi-&#xe929;', /* restore_page */
'mi-&#xe0d1;', /* ring_volume */
'mi-&#xe8b4;', /* room */
'mi-&#xeb49;', /* room_service */
'mi-&#xe418;', /* rotate_90_degrees_ccw */
'mi-&#xe419;', /* rotate_left */
'mi-&#xe41a;', /* rotate_right */
'mi-&#xe920;', /* rounded_corner */
'mi-&#xe328;', /* router */
'mi-&#xe921;', /* rowing */
'mi-&#xe0e5;', /* rss_feed */
'mi-&#xe642;', /* rv_hookup */
'mi-&#xe562;', /* satellite */
'mi-&#xe161;', /* save */
'mi-&#xe329;', /* scanner */
'mi-&#xe8b5;', /* schedule */
'mi-&#xe80c;', /* school */
'mi-&#xe1be;', /* screen_lock_landscape */
'mi-&#xe1bf;', /* screen_lock_portrait */
'mi-&#xe1c0;', /* screen_lock_rotation */
'mi-&#xe1c1;', /* screen_rotation */
'mi-&#xe0e2;', /* screen_share */
'mi-&#xe623;', /* sd_card */
'mi-&#xe1c2;', /* sd_storage */
'mi-&#xe8b6;', /* search */
'mi-&#xe32a;', /* security */
'mi-&#xe162;', /* select_all */
'mi-&#xe163;', /* send */
'mi-&#xe811;', /* sentiment_dissatisfied */
'mi-&#xe812;', /* sentiment_neutral */
'mi-&#xe813;', /* sentiment_satisfied */
'mi-&#xe814;', /* sentiment_very_dissatisfied */
'mi-&#xe815;', /* sentiment_very_satisfied */
'mi-&#xe8b8;', /* settings */
'mi-&#xe8b9;', /* settings_applications */
'mi-&#xe8ba;', /* settings_backup_restore */
'mi-&#xe8bb;', /* settings_bluetooth */
'mi-&#xe8bd;', /* settings_brightness */
'mi-&#xe8bc;', /* settings_cell */
'mi-&#xe8be;', /* settings_ethernet */
'mi-&#xe8bf;', /* settings_input_antenna */
'mi-&#xe8c0;', /* settings_input_component */
'mi-&#xe8c1;', /* settings_input_composite */
'mi-&#xe8c2;', /* settings_input_hdmi */
'mi-&#xe8c3;', /* settings_input_svideo */
'mi-&#xe8c4;', /* settings_overscan */
'mi-&#xe8c5;', /* settings_phone */
'mi-&#xe8c6;', /* settings_power */
'mi-&#xe8c7;', /* settings_remote */
'mi-&#xe1c3;', /* settings_system_daydream */
'mi-&#xe8c8;', /* settings_voice */
'mi-&#xe80d;', /* share */
'mi-&#xe8c9;', /* shop */
'mi-&#xe8ca;', /* shop_two */
'mi-&#xe8cb;', /* shopping_basket */
'mi-&#xe8cc;', /* shopping_cart */
'mi-&#xe261;', /* short_text */
'mi-&#xe6e1;', /* show_chart */
'mi-&#xe043;', /* shuffle */
'mi-&#xe1c8;', /* signal_cellular_4_bar */
'mi-&#xe1cd;', /* signal_cellular_connected_no_internet_4_bar */
'mi-&#xe1ce;', /* signal_cellular_no_sim */
'mi-&#xe1cf;', /* signal_cellular_null */
'mi-&#xe1d0;', /* signal_cellular_off */
'mi-&#xe1d8;', /* signal_wifi_4_bar */
'mi-&#xe1d9;', /* signal_wifi_4_bar_lock */
'mi-&#xe1da;', /* signal_wifi_off */
'mi-&#xe32b;', /* sim_card */
'mi-&#xe624;', /* sim_card_alert */
'mi-&#xe044;', /* skip_next */
'mi-&#xe045;', /* skip_previous */
'mi-&#xe41b;', /* slideshow */
'mi-&#xe068;', /* slow_motion_video */
'mi-&#xe32c;', /* smartphone */
'mi-&#xeb4a;', /* smoke_free */
'mi-&#xeb4b;', /* smoking_rooms */
'mi-&#xe625;', /* sms */
'mi-&#xe626;', /* sms_failed */
'mi-&#xe046;', /* snooze */
'mi-&#xe164;', /* sort */
'mi-&#xe053;', /* sort_by_alpha */
'mi-&#xeb4c;', /* spa */
'mi-&#xe256;', /* space_bar */
'mi-&#xe32d;', /* speaker */
'mi-&#xe32e;', /* speaker_group */
'mi-&#xe8cd;', /* speaker_notes */
'mi-&#xe92a;', /* speaker_notes_off */
'mi-&#xe0d2;', /* speaker_phone */
'mi-&#xe8ce;', /* spellcheck */
'mi-&#xe838;', /* star */
'mi-&#xe83a;', /* star_border */
'mi-&#xe839;', /* star_half */
'mi-&#xe8d0;', /* stars */
'mi-&#xe0d3;', /* stay_current_landscape */
'mi-&#xe0d4;', /* stay_current_portrait */
'mi-&#xe0d5;', /* stay_primary_landscape */
'mi-&#xe0d6;', /* stay_primary_portrait */
'mi-&#xe047;', /* stop */
'mi-&#xe0e3;', /* stop_screen_share */
'mi-&#xe1db;', /* storage */
'mi-&#xe8d1;', /* store */
'mi-&#xe563;', /* store_mall_directory */
'mi-&#xe41c;', /* straighten */
'mi-&#xe56e;', /* streetview */
'mi-&#xe257;', /* strikethrough_s */
'mi-&#xe41d;', /* style */
'mi-&#xe5d9;', /* subdirectory_arrow_left */
'mi-&#xe5da;', /* subdirectory_arrow_right */
'mi-&#xe8d2;', /* subject */
'mi-&#xe064;', /* subscriptions */
'mi-&#xe048;', /* subtitles */
'mi-&#xe56f;', /* subway */
'mi-&#xe8d3;', /* supervisor_account */
'mi-&#xe049;', /* surround_sound */
'mi-&#xe0d7;', /* swap_calls */
'mi-&#xe8d4;', /* swap_horiz */
'mi-&#xe8d5;', /* swap_vert */
'mi-&#xe8d6;', /* swap_vertical_circle */
'mi-&#xe41e;', /* switch_camera */
'mi-&#xe41f;', /* switch_video */
'mi-&#xe627;', /* sync */
'mi-&#xe628;', /* sync_disabled */
'mi-&#xe629;', /* sync_problem */
'mi-&#xe62a;', /* system_update */
'mi-&#xe8d7;', /* system_update_alt */
'mi-&#xe8d8;', /* tab */
'mi-&#xe8d9;', /* tab_unselected */
'mi-&#xe32f;', /* tablet */
'mi-&#xe330;', /* tablet_android */
'mi-&#xe331;', /* tablet_mac */
'mi-&#xe420;', /* tag_faces */
'mi-&#xe62b;', /* tap_and_play */
'mi-&#xe564;', /* terrain */
'mi-&#xe262;', /* text_fields */
'mi-&#xe165;', /* text_format */
'mi-&#xe0d8;', /* textsms */
'mi-&#xe421;', /* texture */
'mi-&#xe8da;', /* theaters */
'mi-&#xe8db;', /* thumb_down */
'mi-&#xe8dc;', /* thumb_up */
'mi-&#xe8dd;', /* thumbs_up_down */
'mi-&#xe62c;', /* time_to_leave */
'mi-&#xe422;', /* timelapse */
'mi-&#xe922;', /* timeline */
'mi-&#xe425;', /* timer */
'mi-&#xe423;', /* timer_10 */
'mi-&#xe424;', /* timer_3 */
'mi-&#xe426;', /* timer_off */
'mi-&#xe264;', /* title */
'mi-&#xe8de;', /* toc */
'mi-&#xe8df;', /* today */
'mi-&#xe8e0;', /* toll */
'mi-&#xe427;', /* tonality */
'mi-&#xe913;', /* touch_app */
'mi-&#xe332;', /* toys */
'mi-&#xe8e1;', /* track_changes */
'mi-&#xe565;', /* traffic */
'mi-&#xe570;', /* train */
'mi-&#xe571;', /* tram */
'mi-&#xe572;', /* transfer_within_a_station */
'mi-&#xe428;', /* transform */
'mi-&#xe8e2;', /* translate */
'mi-&#xe8e3;', /* trending_down */
'mi-&#xe8e4;', /* trending_flat */
'mi-&#xe8e5;', /* trending_up */
'mi-&#xe429;', /* tune */
'mi-&#xe8e6;', /* turned_in */
'mi-&#xe8e7;', /* turned_in_not */
'mi-&#xe333;', /* tv */
'mi-&#xe169;', /* unarchive */
'mi-&#xe166;', /* undo */
'mi-&#xe5d6;', /* unfold_less */
'mi-&#xe5d7;', /* unfold_more */
'mi-&#xe923;', /* update */
'mi-&#xe1e0;', /* usb */
'mi-&#xe8e8;', /* verified_user */
'mi-&#xe258;', /* vertical_align_bottom */
'mi-&#xe259;', /* vertical_align_center */
'mi-&#xe25a;', /* vertical_align_top */
'mi-&#xe62d;', /* vibration */
'mi-&#xe070;', /* video_call */
'mi-&#xe071;', /* video_label */
'mi-&#xe04a;', /* video_library */
'mi-&#xe04b;', /* videocam */
'mi-&#xe04c;', /* videocam_off */
'mi-&#xe338;', /* videogame_asset */
'mi-&#xe8e9;', /* view_agenda */
'mi-&#xe8ea;', /* view_array */
'mi-&#xe8eb;', /* view_carousel */
'mi-&#xe8ec;', /* view_column */
'mi-&#xe42a;', /* view_comfy */
'mi-&#xe42b;', /* view_compact */
'mi-&#xe8ed;', /* view_day */
'mi-&#xe8ee;', /* view_headline */
'mi-&#xe8ef;', /* view_list */
'mi-&#xe8f0;', /* view_module */
'mi-&#xe8f1;', /* view_quilt */
'mi-&#xe8f2;', /* view_stream */
'mi-&#xe8f3;', /* view_week */
'mi-&#xe435;', /* vignette */
'mi-&#xe8f4;', /* visibility */
'mi-&#xe8f5;', /* visibility_off */
'mi-&#xe62e;', /* voice_chat */
'mi-&#xe0d9;', /* voicemail */
'mi-&#xe04d;', /* volume_down */
'mi-&#xe04e;', /* volume_mute */
'mi-&#xe04f;', /* volume_off */
'mi-&#xe050;', /* volume_up */
'mi-&#xe0da;', /* vpn_key */
'mi-&#xe62f;', /* vpn_lock */
'mi-&#xe1bc;', /* wallpaper */
'mi-&#xe002;', /* warning */
'mi-&#xe334;', /* watch */
'mi-&#xe924;', /* watch_later */
'mi-&#xe42c;', /* wb_auto */
'mi-&#xe42d;', /* wb_cloudy */
'mi-&#xe42e;', /* wb_incandescent */
'mi-&#xe436;', /* wb_iridescent */
'mi-&#xe430;', /* wb_sunny */
'mi-&#xe63d;', /* wc */
'mi-&#xe051;', /* web */
'mi-&#xe069;', /* web_asset */
'mi-&#xe16b;', /* weekend */
'mi-&#xe80e;', /* whatshot */
'mi-&#xe1bd;', /* widgets */
'mi-&#xe63e;', /* wifi */
'mi-&#xe1e1;', /* wifi_lock */
'mi-&#xe1e2;', /* wifi_tethering */
'mi-&#xe8f9;', /* work */
'mi-&#xe25b;', /* wrap_text */
'mi-&#xe8fa;', /* youtube_searched_for */
'mi-&#xe8ff;', /* zoom_in */
'mi-&#xe900;', /* zoom_out */
'mi-&#xe56b;', /* zoom_out_map */
'mi-&#xe84d;', /* 3d_rotation */
'mi-&#xeb3b;', /* ac_unit */
'mi-&#xe190;', /* access_alarm */
'mi-&#xe191;', /* access_alarms */
'mi-&#xe192;', /* access_time */
'mi-&#xe84e;', /* accessibility */
'mi-&#xe914;', /* accessible */
'mi-&#xe84f;', /* account_balance */
'mi-&#xe850;', /* account_balance_wallet */
'mi-&#xe851;', /* account_box */
'mi-&#xe853;', /* account_circle */
'mi-&#xe60e;', /* adb */
'mi-&#xe145;', /* add */
'mi-&#xe439;', /* add_a_photo */
'mi-&#xe193;', /* add_alarm */
'mi-&#xe003;', /* add_alert */
'mi-&#xe146;', /* add_box */
'mi-&#xe147;', /* add_circle */
'mi-&#xe148;', /* add_circle_outline */
'mi-&#xe567;', /* add_location */
'mi-&#xe854;', /* add_shopping_cart */
'mi-&#xe39d;', /* add_to_photos */
'mi-&#xe05c;', /* add_to_queue */
'mi-&#xe39e;', /* adjust */
'mi-&#xe630;', /* airline_seat_flat */
'mi-&#xe631;', /* airline_seat_flat_angled */
'mi-&#xe632;', /* airline_seat_individual_suite */
'mi-&#xe633;', /* airline_seat_legroom_extra */
'mi-&#xe634;', /* airline_seat_legroom_normal */
'mi-&#xe635;', /* airline_seat_legroom_reduced */
'mi-&#xe636;', /* airline_seat_recline_extra */
'mi-&#xe637;', /* airline_seat_recline_normal */
'mi-&#xe195;', /* airplanemode_active */
'mi-&#xe194;', /* airplanemode_inactive */
'mi-&#xe055;', /* airplay */
'mi-&#xeb3c;', /* airport_shuttle */
'mi-&#xe855;', /* alarm */
'mi-&#xe856;', /* alarm_add */
'mi-&#xe857;', /* alarm_off */
'mi-&#xe858;', /* alarm_on */
'mi-&#xe019;', /* album */
'mi-&#xeb3d;', /* all_inclusive */
'mi-&#xe90b;', /* all_out */
'mi-&#xe859;', /* android */
'mi-&#xe85a;', /* announcement */
'mi-&#xe5c3;', /* apps */
'mi-&#xe149;', /* archive */
'mi-&#xe5c4;', /* arrow_back */
'mi-&#xe5db;', /* arrow_downward */
'mi-&#xe5c5;', /* arrow_drop_down */
'mi-&#xe5c6;', /* arrow_drop_down_circle */
'mi-&#xe5c7;', /* arrow_drop_up */
'mi-&#xe5c8;', /* arrow_forward */
'mi-&#xe5d8;', /* arrow_upward */
'mi-&#xe060;', /* art_track */
'mi-&#xe85b;', /* aspect_ratio */
'mi-&#xe85c;', /* assessment */
'mi-&#xe85d;', /* assignment */
'mi-&#xe85e;', /* assignment_ind */
'mi-&#xe85f;', /* assignment_late */
'mi-&#xe860;', /* assignment_return */
'mi-&#xe861;', /* assignment_returned */
'mi-&#xe862;', /* assignment_turned_in */
'mi-&#xe39f;', /* assistant */
'mi-&#xe3a0;', /* assistant_photo */
'mi-&#xe226;', /* attach_file */
'mi-&#xe227;', /* attach_money */
'mi-&#xe2bc;', /* attachment */
'mi-&#xe3a1;', /* audiotrack */
'mi-&#xe863;', /* autorenew */
'mi-&#xe01b;', /* av_timer */
'mi-&#xe14a;', /* backspace */
'mi-&#xe864;', /* backup */
'mi-&#xe19c;', /* battery_alert */
'mi-&#xe1a3;', /* battery_charging_full */
'mi-&#xe1a4;', /* battery_full */
'mi-&#xe1a5;', /* battery_std */
'mi-&#xe1a6;', /* battery_unknown */
'mi-&#xeb3e;', /* beach_access */
'mi-&#xe52d;', /* beenhere */
'mi-&#xe14b;', /* block */
'mi-&#xe1a7;', /* bluetooth */
'mi-&#xe60f;', /* bluetooth_audio */
'mi-&#xe1a8;', /* bluetooth_connected */
'mi-&#xe1a9;', /* bluetooth_disabled */
'mi-&#xe1aa;', /* bluetooth_searching */
'mi-&#xe3a2;', /* blur_circular */
'mi-&#xe3a3;', /* blur_linear */
'mi-&#xe3a4;', /* blur_off */
'mi-&#xe3a5;', /* blur_on */
'mi-&#xe865;', /* book */
'mi-&#xe866;', /* bookmark */
'mi-&#xe867;', /* bookmark_border */
'mi-&#xe228;', /* border_all */
'mi-&#xe229;', /* border_bottom */
'mi-&#xe22a;', /* border_clear */
'mi-&#xe22b;', /* border_color */
'mi-&#xe22c;', /* border_horizontal */
'mi-&#xe22d;', /* border_inner */
'mi-&#xe22e;', /* border_left */
'mi-&#xe22f;', /* border_outer */
'mi-&#xe230;', /* border_right */
'mi-&#xe231;', /* border_style */
'mi-&#xe232;', /* border_top */
'mi-&#xe233;', /* border_vertical */
'mi-&#xe06b;', /* branding_watermark */
'mi-&#xe3a6;', /* brightness_1 */
'mi-&#xe3a7;', /* brightness_2 */
'mi-&#xe3a8;', /* brightness_3 */
'mi-&#xe3a9;', /* brightness_4 */
'mi-&#xe3aa;', /* brightness_5 */
'mi-&#xe3ab;', /* brightness_6 */
'mi-&#xe3ac;', /* brightness_7 */
'mi-&#xe1ab;', /* brightness_auto */
'mi-&#xe1ac;', /* brightness_high */
'mi-&#xe1ad;', /* brightness_low */
'mi-&#xe1ae;', /* brightness_medium */
'mi-&#xe3ad;', /* broken_image */
'mi-&#xe3ae;', /* brush */
'mi-&#xe6dd;', /* bubble_chart */
'mi-&#xe868;', /* bug_report */
'mi-&#xe869;', /* build */
'mi-&#xe43c;', /* burst_mode */
'mi-&#xe0af;', /* business */
'mi-&#xeb3f;', /* business_center */
'mi-&#xe86a;', /* cached */
'mi-&#xe7e9;', /* cake */
'mi-&#xe0b0;', /* call */
'mi-&#xe0b1;', /* call_end */
'mi-&#xe0b2;', /* call_made */
'mi-&#xe0b3;', /* call_merge */
'mi-&#xe0b4;', /* call_missed */
'mi-&#xe0e4;', /* call_missed_outgoing */
'mi-&#xe0b5;', /* call_received */
'mi-&#xe0b6;', /* call_split */
'mi-&#xe06c;', /* call_to_action */
'mi-&#xe3af;', /* camera */
'mi-&#xe3b0;', /* camera_alt */
'mi-&#xe8fc;', /* camera_enhance */
'mi-&#xe3b1;', /* camera_front */
'mi-&#xe3b2;', /* camera_rear */
'mi-&#xe3b3;', /* camera_roll */
'mi-&#xe5c9;', /* cancel */
'mi-&#xe8f6;', /* card_giftcard */
'mi-&#xe8f7;', /* card_membership */
'mi-&#xe8f8;', /* card_travel */
'mi-&#xeb40;', /* casino */
'mi-&#xe307;', /* cast */
'mi-&#xe308;', /* cast_connected */
'mi-&#xe3b4;', /* center_focus_strong */
'mi-&#xe3b5;', /* center_focus_weak */
'mi-&#xe86b;', /* change_history */
'mi-&#xe0b7;', /* chat */
'mi-&#xe0ca;', /* chat_bubble */
'mi-&#xe0cb;', /* chat_bubble_outline */
'mi-&#xe5ca;', /* check */
'mi-&#xe834;', /* check_box */
'mi-&#xe835;', /* check_box_outline_blank */
'mi-&#xe86c;', /* check_circle */
'mi-&#xe5cb;', /* chevron_left */
'mi-&#xe5cc;', /* chevron_right */
'mi-&#xeb41;', /* child_care */
'mi-&#xeb42;', /* child_friendly */
'mi-&#xe86d;', /* chrome_reader_mode */
'mi-&#xe86e;', /* class */
'mi-&#xe14c;', /* clear */
'mi-&#xe0b8;', /* clear_all */
'mi-&#xe5cd;', /* close */
'mi-&#xe01c;', /* closed_caption */
'mi-&#xe2bd;', /* cloud */
'mi-&#xe2be;', /* cloud_circle */
'mi-&#xe2bf;', /* cloud_done */
'mi-&#xe2c0;', /* cloud_download */
'mi-&#xe2c1;', /* cloud_off */
'mi-&#xe2c2;', /* cloud_queue */
'mi-&#xe2c3;', /* cloud_upload */
'mi-&#xe86f;', /* code */
'mi-&#xe3b6;', /* collections */
'mi-&#xe431;', /* collections_bookmark */
'mi-&#xe3b7;', /* color_lens */
'mi-&#xe3b8;', /* colorize */
'mi-&#xe0b9;', /* comment */
'mi-&#xe3b9;', /* compare */
'mi-&#xe915;', /* compare_arrows */
'mi-&#xe30a;', /* computer */
'mi-&#xe638;', /* confirmation_number */
'mi-&#xe0d0;', /* contact_mail */
'mi-&#xe0cf;', /* contact_phone */
'mi-&#xe0ba;', /* contacts */
'mi-&#xe14d;', /* content_copy */
'mi-&#xe14e;', /* content_cut */
'mi-&#xe14f;', /* content_paste */
'mi-&#xe3ba;', /* control_point */
'mi-&#xe3bb;', /* control_point_duplicate */
'mi-&#xe90c;', /* copyright */
'mi-&#xe150;', /* create */
'mi-&#xe2cc;', /* create_new_folder */
'mi-&#xe870;', /* credit_card */
'mi-&#xe3be;', /* crop */
'mi-&#xe3bc;', /* crop_16_9 */
'mi-&#xe3bd;', /* crop_3_2 */
'mi-&#xe3bf;', /* crop_5_4 */
'mi-&#xe3c0;', /* crop_7_5 */
'mi-&#xe3c1;', /* crop_din */
'mi-&#xe3c2;', /* crop_free */
'mi-&#xe3c3;', /* crop_landscape */
'mi-&#xe3c4;', /* crop_original */
'mi-&#xe3c5;', /* crop_portrait */
'mi-&#xe437;', /* crop_rotate */
'mi-&#xe3c6;', /* crop_square */
'mi-&#xe871;', /* dashboard */
'mi-&#xe1af;', /* data_usage */
'mi-&#xe916;', /* date_range */
'mi-&#xe3c7;', /* dehaze */
'mi-&#xe872;', /* delete */
'mi-&#xe92b;', /* delete_forever */
'mi-&#xe16c;', /* delete_sweep */
'mi-&#xe873;', /* description */
'mi-&#xe30b;', /* desktop_mac */
'mi-&#xe30c;', /* desktop_windows */
'mi-&#xe3c8;', /* details */
'mi-&#xe30d;', /* developer_board */
'mi-&#xe1b0;', /* developer_mode */
'mi-&#xe335;', /* device_hub */
'mi-&#xe1b1;', /* devices */
'mi-&#xe337;', /* devices_other */
'mi-&#xe0bb;', /* dialer_sip */
'mi-&#xe0bc;', /* dialpad */
'mi-&#xe52e;', /* directions */
'mi-&#xe52f;', /* directions_bike */
'mi-&#xe532;', /* directions_boat */
'mi-&#xe530;', /* directions_bus */
'mi-&#xe531;', /* directions_car */
'mi-&#xe534;', /* directions_railway */
'mi-&#xe566;', /* directions_run */
'mi-&#xe533;', /* directions_subway */
'mi-&#xe535;', /* directions_transit */
'mi-&#xe536;', /* directions_walk */
'mi-&#xe610;', /* disc_full */
'mi-&#xe875;', /* dns */
'mi-&#xe612;', /* do_not_disturb */
'mi-&#xe611;', /* do_not_disturb_alt */
'mi-&#xe643;', /* do_not_disturb_off */
'mi-&#xe644;', /* do_not_disturb_on */
'mi-&#xe30e;', /* dock */
'mi-&#xe7ee;', /* domain */
'mi-&#xe876;', /* done */
'mi-&#xe877;', /* done_all */
'mi-&#xe917;', /* donut_large */
'mi-&#xe918;', /* donut_small */
'mi-&#xe151;', /* drafts */
'mi-&#xe25d;', /* drag_handle */
'mi-&#xe613;', /* drive_eta */
'mi-&#xe1b2;', /* dvr */
'mi-&#xe3c9;', /* edit */
'mi-&#xe568;', /* edit_location */
'mi-&#xe8fb;', /* eject */
'mi-&#xe0be;', /* email */
'mi-&#xe63f;', /* enhanced_encryption */
'mi-&#xe01d;', /* equalizer */
'mi-&#xe000;', /* error */
'mi-&#xe001;', /* error_outline */
'mi-&#xe926;', /* euro_symbol */
'mi-&#xe56d;', /* ev_station */
'mi-&#xe878;', /* event */
'mi-&#xe614;', /* event_available */
'mi-&#xe615;', /* event_busy */
'mi-&#xe616;', /* event_note */
'mi-&#xe903;', /* event_seat */
'mi-&#xe879;', /* exit_to_app */
'mi-&#xe5ce;', /* expand_less */
'mi-&#xe5cf;', /* expand_more */
'mi-&#xe01e;', /* explicit */
'mi-&#xe87a;', /* explore */
'mi-&#xe3ca;', /* exposure */
'mi-&#xe3cb;', /* exposure_neg_1 */
'mi-&#xe3cc;', /* exposure_neg_2 */
'mi-&#xe3cd;', /* exposure_plus_1 */
'mi-&#xe3ce;', /* exposure_plus_2 */
'mi-&#xe3cf;', /* exposure_zero */
'mi-&#xe87b;', /* extension */
'mi-&#xe87c;', /* face */
'mi-&#xe01f;', /* fast_forward */
'mi-&#xe020;', /* fast_rewind */
'mi-&#xe87d;', /* favorite */
'mi-&#xe87e;', /* favorite_border */
'mi-&#xe06d;', /* featured_play_list */
'mi-&#xe06e;', /* featured_video */
'mi-&#xe87f;', /* feedback */
'mi-&#xe05d;', /* fiber_dvr */
'mi-&#xe061;', /* fiber_manual_record */
'mi-&#xe05e;', /* fiber_new */
'mi-&#xe06a;', /* fiber_pin */
'mi-&#xe062;', /* fiber_smart_record */
'mi-&#xe2c4;', /* file_download */
'mi-&#xe2c6;', /* file_upload */
'mi-&#xe3d3;', /* filter */
'mi-&#xe3d0;', /* filter_1 */
'mi-&#xe3d1;', /* filter_2 */
'mi-&#xe3d2;', /* filter_3 */
'mi-&#xe3d4;', /* filter_4 */
'mi-&#xe3d5;', /* filter_5 */
'mi-&#xe3d6;', /* filter_6 */
'mi-&#xe3d7;', /* filter_7 */
'mi-&#xe3d8;', /* filter_8 */
'mi-&#xe3d9;', /* filter_9 */
'mi-&#xe3da;', /* filter_9_plus */
'mi-&#xe3db;', /* filter_b_and_w */
'mi-&#xe3dc;', /* filter_center_focus */
'mi-&#xe3dd;', /* filter_drama */
'mi-&#xe3de;', /* filter_frames */
'mi-&#xe3df;', /* filter_hdr */
'mi-&#xe152;', /* filter_list */
'mi-&#xe3e0;', /* filter_none */
'mi-&#xe3e2;', /* filter_tilt_shift */
'mi-&#xe3e3;', /* filter_vintage */
'mi-&#xe880;', /* find_in_page */
'mi-&#xe881;', /* find_replace */
'mi-&#xe90d;', /* fingerprint */
'mi-&#xe5dc;', /* first_page */
'mi-&#xeb43;', /* fitness_center */
'mi-&#xe153;', /* flag */
'mi-&#xe3e4;', /* flare */
'mi-&#xe3e5;', /* flash_auto */
'mi-&#xe3e6;', /* flash_off */
'mi-&#xe3e7;', /* flash_on */
'mi-&#xe539;', /* flight */
'mi-&#xe904;', /* flight_land */
'mi-&#xe905;', /* flight_takeoff */
'mi-&#xe3e8;', /* flip */
'mi-&#xe882;', /* flip_to_back */
'mi-&#xe883;', /* flip_to_front */
'mi-&#xe2c7;', /* folder */
'mi-&#xe2c8;', /* folder_open */
'mi-&#xe2c9;', /* folder_shared */
'mi-&#xe617;', /* folder_special */
'mi-&#xe167;', /* font_download */
'mi-&#xe234;', /* format_align_center */
'mi-&#xe235;', /* format_align_justify */
'mi-&#xe236;', /* format_align_left */
'mi-&#xe237;', /* format_align_right */
'mi-&#xe238;', /* format_bold */
'mi-&#xe239;', /* format_clear */
'mi-&#xe23a;', /* format_color_fill */
'mi-&#xe23b;', /* format_color_reset */
'mi-&#xe23c;', /* format_color_text */
'mi-&#xe23d;', /* format_indent_decrease */
'mi-&#xe23e;', /* format_indent_increase */
'mi-&#xe23f;', /* format_italic */
'mi-&#xe240;', /* format_line_spacing */
'mi-&#xe241;', /* format_list_bulleted */
'mi-&#xe242;', /* format_list_numbered */
'mi-&#xe243;', /* format_paint */
'mi-&#xe244;', /* format_quote */
'mi-&#xe25e;', /* format_shapes */
'mi-&#xe245;', /* format_size */
'mi-&#xe246;', /* format_strikethrough */
'mi-&#xe247;', /* format_textdirection_l_to_r */
'mi-&#xe248;', /* format_textdirection_r_to_l */
'mi-&#xe249;', /* format_underlined */
'mi-&#xe0bf;', /* forum */
'mi-&#xe154;', /* forward */
'mi-&#xe056;', /* forward_10 */
'mi-&#xe057;', /* forward_30 */
'mi-&#xe058;', /* forward_5 */
'mi-&#xeb44;', /* free_breakfast */
'mi-&#xe5d0;', /* fullscreen */
'mi-&#xe5d1;', /* fullscreen_exit */
'mi-&#xe24a;', /* functions */
'mi-&#xe927;', /* g_translate */
'mi-&#xe30f;', /* gamepad */
'mi-&#xe021;', /* games */
'mi-&#xe90e;', /* gavel */
'mi-&#xe155;', /* gesture */
'mi-&#xe884;', /* get_app */
'mi-&#xe908;', /* gif */
'mi-&#xeb45;', /* golf_course */
'mi-&#xe1b3;', /* gps_fixed */
'mi-&#xe1b4;', /* gps_not_fixed */
'mi-&#xe1b5;', /* gps_off */
'mi-&#xe885;', /* grade */
'mi-&#xe3e9;', /* gradient */
'mi-&#xe3ea;', /* grain */
'mi-&#xe1b8;', /* graphic_eq */
'mi-&#xe3eb;', /* grid_off */
'mi-&#xe3ec;', /* grid_on */
'mi-&#xe7ef;', /* group */
'mi-&#xe7f0;', /* group_add */
'mi-&#xe886;', /* group_work */
'mi-&#xe052;', /* hd */
'mi-&#xe3ed;', /* hdr_off */
'mi-&#xe3ee;', /* hdr_on */
'mi-&#xe3f1;', /* hdr_strong */
'mi-&#xe3f2;', /* hdr_weak */
'mi-&#xe310;', /* headset */
'mi-&#xe311;', /* headset_mic */
'mi-&#xe3f3;', /* healing */
'mi-&#xe023;', /* hearing */
'mi-&#xe887;', /* help */
'mi-&#xe8fd;', /* help_outline */
'mi-&#xe024;', /* high_quality */
'mi-&#xe25f;', /* highlight */
'mi-&#xe888;', /* highlight_off */
'mi-&#xe889;', /* history */
'mi-&#xe88a;', /* home */
'mi-&#xeb46;', /* hot_tub */
'mi-&#xe53a;', /* hotel */
'mi-&#xe88b;', /* hourglass_empty */
'mi-&#xe88c;', /* hourglass_full */
'mi-&#xe902;', /* http */
'mi-&#xe88d;', /* https */
'mi-&#xe3f4;', /* image */
'mi-&#xe3f5;', /* image_aspect_ratio */
'mi-&#xe0e0;', /* import_contacts */
'mi-&#xe0c3;', /* import_export */
'mi-&#xe912;', /* important_devices */
'mi-&#xe156;', /* inbox */
'mi-&#xe909;', /* indeterminate_check_box */
'mi-&#xe88e;', /* info */
'mi-&#xe88f;', /* info_outline */
'mi-&#xe890;', /* input */
'mi-&#xe24b;', /* insert_chart */
'mi-&#xe24c;', /* insert_comment */
'mi-&#xe24d;', /* insert_drive_file */
'mi-&#xe24e;', /* insert_emoticon */
'mi-&#xe24f;', /* insert_invitation */
'mi-&#xe250;', /* insert_link */
'mi-&#xe251;', /* insert_photo */
'mi-&#xe891;', /* invert_colors */
'mi-&#xe0c4;', /* invert_colors_off */
'mi-&#xe3f6;', /* iso */
'mi-&#xe312;', /* keyboard */
'mi-&#xe313;', /* keyboard_arrow_down */
'mi-&#xe314;', /* keyboard_arrow_left */
'mi-&#xe315;', /* keyboard_arrow_right */
'mi-&#xe316;', /* keyboard_arrow_up */
'mi-&#xe317;', /* keyboard_backspace */
'mi-&#xe318;', /* keyboard_capslock */
'mi-&#xe31a;', /* keyboard_hide */
'mi-&#xe31b;', /* keyboard_return */
'mi-&#xe31c;', /* keyboard_tab */
'mi-&#xe31d;', /* keyboard_voice */
'mi-&#xeb47;', /* kitchen */
'mi-&#xe892;', /* label */
'mi-&#xe893;', /* label_outline */
'mi-&#xe3f7;', /* landscape */
'mi-&#xe894;', /* language */
'mi-&#xe31e;', /* laptop */
'mi-&#xe31f;', /* laptop_chromebook */
'mi-&#xe320;', /* laptop_mac */
'mi-&#xe321;', /* laptop_windows */
'mi-&#xe5dd;', /* last_page */
'mi-&#xe895;', /* launch */
'mi-&#xe53b;', /* layers */
'mi-&#xe53c;', /* layers_clear */
'mi-&#xe3f8;', /* leak_add */
'mi-&#xe3f9;', /* leak_remove */
'mi-&#xe3fa;', /* lens */
'mi-&#xe02e;', /* library_add */
'mi-&#xe02f;', /* library_books */
'mi-&#xe030;', /* library_music */
'mi-&#xe90f;', /* lightbulb_outline */
'mi-&#xe919;', /* line_style */
'mi-&#xe91a;', /* line_weight */
'mi-&#xe260;', /* linear_scale */
'mi-&#xe157;', /* link */
'mi-&#xe438;', /* linked_camera */
'mi-&#xe896;', /* list */
'mi-&#xe0c6;', /* live_help */
'mi-&#xe639;', /* live_tv */
'mi-&#xe53f;', /* local_activity */
'mi-&#xe53d;', /* local_airport */
'mi-&#xe53e;', /* local_atm */
'mi-&#xe540;', /* local_bar */
'mi-&#xe541;', /* local_cafe */
'mi-&#xe542;', /* local_car_wash */
'mi-&#xe543;', /* local_convenience_store */
'mi-&#xe556;', /* local_dining */
'mi-&#xe544;', /* local_drink */
'mi-&#xe545;', /* local_florist */
'mi-&#xe546;', /* local_gas_station */
'mi-&#xe547;', /* local_grocery_store */
'mi-&#xe548;', /* local_hospital */
'mi-&#xe549;', /* local_hotel */
'mi-&#xe54a;', /* local_laundry_service */
'mi-&#xe54b;', /* local_library */
'mi-&#xe54c;', /* local_mall */
'mi-&#xe54d;', /* local_movies */
'mi-&#xe54e;', /* local_offer */
'mi-&#xe54f;', /* local_parking */
'mi-&#xe550;', /* local_pharmacy */
'mi-&#xe551;', /* local_phone */
'mi-&#xe552;', /* local_pizza */
'mi-&#xe553;', /* local_play */
'mi-&#xe554;', /* local_post_office */
'mi-&#xe555;', /* local_printshop */
'mi-&#xe557;', /* local_see */
'mi-&#xe558;', /* local_shipping */
'mi-&#xe559;', /* local_taxi */
'mi-&#xe7f1;', /* location_city */
'mi-&#xe1b6;', /* location_disabled */
'mi-&#xe0c7;', /* location_off */
'mi-&#xe0c8;', /* location_on */
'mi-&#xe1b7;', /* location_searching */
'mi-&#xe897;', /* lock */
'mi-&#xe898;', /* lock_open */
'mi-&#xe899;', /* lock_outline */
'mi-&#xe3fc;', /* looks */
'mi-&#xe3fb;', /* looks_3 */
'mi-&#xe3fd;', /* looks_4 */
'mi-&#xe3fe;', /* looks_5 */
'mi-&#xe3ff;', /* looks_6 */
'mi-&#xe400;', /* looks_one */
'mi-&#xe401;', /* looks_two */
'mi-&#xe028;', /* loop */
'mi-&#xe402;', /* loupe */
'mi-&#xe16d;', /* low_priority */
'mi-&#xe89a;', /* loyalty */
'mi-&#xe158;', /* mail */
'mi-&#xe0e1;', /* mail_outline */
'mi-&#xe55b;', /* map */
'mi-&#xe159;', /* markunread */
'mi-&#xe89b;', /* markunread_mailbox */
'mi-&#xe322;', /* memory */
'mi-&#xe5d2;', /* menu */
'mi-&#xe252;', /* merge_type */
'mi-&#xe0c9;', /* message */
'mi-&#xe029;', /* mic */
'mi-&#xe02a;', /* mic_none */
'mi-&#xe02b;', /* mic_off */
'mi-&#xe618;', /* mms */
'mi-&#xe253;', /* mode_comment */
'mi-&#xe254;', /* mode_edit */
'mi-&#xe263;', /* monetization_on */
'mi-&#xe25c;', /* money_off */
'mi-&#xe403;', /* monochrome_photos */
'mi-&#xe7f2;', /* mood */
'mi-&#xe7f3;', /* mood_bad */
'mi-&#xe619;', /* more */
'mi-&#xe5d3;', /* more_horiz */
'mi-&#xe5d4;', /* more_vert */
'mi-&#xe91b;', /* motorcycle */
'mi-&#xe323;', /* mouse */
'mi-&#xe168;', /* move_to_inbox */
'mi-&#xe02c;', /* movie */
'mi-&#xe404;', /* movie_creation */
'mi-&#xe43a;', /* movie_filter */
'mi-&#xe6df;', /* multiline_chart */
'mi-&#xe405;', /* music_note */
'mi-&#xe063;', /* music_video */
'mi-&#xe55c;', /* my_location */
'mi-&#xe406;', /* nature */
'mi-&#xe407;', /* nature_people */
'mi-&#xe408;', /* navigate_before */
'mi-&#xe409;', /* navigate_next */
'mi-&#xe55d;', /* navigation */
'mi-&#xe569;', /* near_me */
'mi-&#xe1b9;', /* network_cell */
'mi-&#xe640;', /* network_check */
'mi-&#xe61a;', /* network_locked */
'mi-&#xe1ba;', /* network_wifi */
'mi-&#xe031;', /* new_releases */
'mi-&#xe16a;', /* next_week */
'mi-&#xe1bb;', /* nfc */
'mi-&#xe641;', /* no_encryption */
'mi-&#xe0cc;', /* no_sim */
'mi-&#xe033;', /* not_interested */
'mi-&#xe06f;', /* note */
'mi-&#xe89c;', /* note_add */
'mi-&#xe7f4;', /* notifications */
'mi-&#xe7f7;', /* notifications_active */
'mi-&#xe7f5;', /* notifications_none */
'mi-&#xe7f6;', /* notifications_off */
'mi-&#xe7f8;', /* notifications_paused */
'mi-&#xe90a;', /* offline_pin */
'mi-&#xe63a;', /* ondemand_video */
'mi-&#xe91c;', /* opacity */
'mi-&#xe89d;', /* open_in_browser */
'mi-&#xe89e;', /* open_in_new */
'mi-&#xe89f;', /* open_with */
'mi-&#xe7f9;', /* pages */
'mi-&#xe8a0;', /* pageview */
'mi-&#xe40a;', /* palette */
'mi-&#xe925;', /* pan_tool */
'mi-&#xe40b;', /* panorama */
'mi-&#xe40c;', /* panorama_fish_eye */
'mi-&#xe40d;', /* panorama_horizontal */
'mi-&#xe40e;', /* panorama_vertical */
'mi-&#xe40f;', /* panorama_wide_angle */
'mi-&#xe7fa;', /* party_mode */
'mi-&#xe034;', /* pause */
'mi-&#xe035;', /* pause_circle_filled */
'mi-&#xe036;', /* pause_circle_outline */
'mi-&#xe8a1;', /* payment */
'mi-&#xe7fb;', /* people */
'mi-&#xe7fc;', /* people_outline */
'mi-&#xe8a2;', /* perm_camera_mic */
'mi-&#xe8a3;', /* perm_contact_calendar */
'mi-&#xe8a4;', /* perm_data_setting */
'mi-&#xe8a5;', /* perm_device_information */
'mi-&#xe8a6;', /* perm_identity */
'mi-&#xe8a7;', /* perm_media */
'mi-&#xe8a8;', /* perm_phone_msg */
'mi-&#xe8a9;', /* perm_scan_wifi */
'mi-&#xe7fd;', /* person */
'mi-&#xe7fe;', /* person_add */
'mi-&#xe7ff;', /* person_outline */
'mi-&#xe55a;', /* person_pin */
'mi-&#xe56a;', /* person_pin_circle */
'mi-&#xe63b;', /* personal_video */
'mi-&#xe91d;', /* pets */
'mi-&#xe0cd;', /* phone */
'mi-&#xe324;', /* phone_android */
'mi-&#xe61b;', /* phone_bluetooth_speaker */
'mi-&#xe61c;', /* phone_forwarded */
'mi-&#xe61d;', /* phone_in_talk */
'mi-&#xe325;', /* phone_iphone */
'mi-&#xe61e;', /* phone_locked */
'mi-&#xe61f;', /* phone_missed */
'mi-&#xe620;', /* phone_paused */
'mi-&#xe326;', /* phonelink */
'mi-&#xe0db;', /* phonelink_erase */
'mi-&#xe0dc;', /* phonelink_lock */
'mi-&#xe327;', /* phonelink_off */
'mi-&#xe0dd;', /* phonelink_ring */
'mi-&#xe0de;', /* phonelink_setup */
'mi-&#xe410;', /* photo */
'mi-&#xe411;', /* photo_album */
'mi-&#xe412;', /* photo_camera */
'mi-&#xe43b;', /* photo_filter */
'mi-&#xe413;', /* photo_library */
'mi-&#xe432;', /* photo_size_select_actual */
'mi-&#xe433;', /* photo_size_select_large */
'mi-&#xe434;', /* photo_size_select_small */
'mi-&#xe415;', /* picture_as_pdf */
'mi-&#xe8aa;', /* picture_in_picture */
'mi-&#xe911;', /* picture_in_picture_alt */
'mi-&#xe6c4;', /* pie_chart */
'mi-&#xe6c5;', /* pie_chart_outlined */
'mi-&#xe55e;', /* pin_drop */
'mi-&#xe55f;', /* place */
'mi-&#xe037;', /* play_arrow */
'mi-&#xe038;', /* play_circle_filled */
'mi-&#xe039;', /* play_circle_outline */
'mi-&#xe906;', /* play_for_work */
'mi-&#xe03b;', /* playlist_add */
'mi-&#xe065;', /* playlist_add_check */
'mi-&#xe05f;', /* playlist_play */
'mi-&#xe800;', /* plus_one */
'mi-&#xe801;', /* poll */
'mi-&#xe8ab;', /* polymer */
'mi-&#xeb48;', /* pool */
'mi-&#xe0ce;', /* portable_wifi_off */
'mi-&#xe416;', /* portrait */
'mi-&#xe63c;', /* power */
'mi-&#xe336;', /* power_input */
'mi-&#xe8ac;', /* power_settings_new */
'mi-&#xe91e;', /* pregnant_woman */
'mi-&#xe0df;', /* present_to_all */
'mi-&#xe8ad;', /* print */
'mi-&#xe645;', /* priority_high */
'mi-&#xe80b;', /* public */
'mi-&#xe255;', /* publish */
'mi-&#xe8ae;', /* query_builder */
'mi-&#xe8af;', /* question_answer */
'mi-&#xe03c;', /* queue */
'mi-&#xe03d;', /* queue_music */
'mi-&#xe066;', /* queue_play_next */
'mi-&#xe03e;', /* radio */
'mi-&#xe837;', /* radio_button_checked */
'mi-&#xe836;', /* radio_button_unchecked */
'mi-&#xe560;', /* rate_review */
'mi-&#xe8b0;', /* receipt */
'mi-&#xe03f;', /* recent_actors */
'mi-&#xe91f;', /* record_voice_over */
'mi-&#xe8b1;', /* redeem */
'mi-&#xe15a;', /* redo */
'mi-&#xe5d5;', /* refresh */
'mi-&#xe15b;', /* remove */
'mi-&#xe15c;', /* remove_circle */
'mi-&#xe15d;', /* remove_circle_outline */
'mi-&#xe067;', /* remove_from_queue */
'mi-&#xe417;', /* remove_red_eye */
'mi-&#xe928;', /* remove_shopping_cart */
'mi-&#xe8fe;', /* reorder */
'mi-&#xe040;', /* repeat */
'mi-&#xe041;', /* repeat_one */
'mi-&#xe042;', /* replay */
'mi-&#xe059;', /* replay_10 */
'mi-&#xe05a;', /* replay_30 */
'mi-&#xe05b;', /* replay_5 */
'mi-&#xe15e;', /* reply */
'mi-&#xe15f;', /* reply_all */
'mi-&#xe160;', /* report */
'mi-&#xe8b2;', /* report_problem */
'mi-&#xe56c;', /* restaurant */
'mi-&#xe561;', /* restaurant_menu */
'mi-&#xe8b3;', /* restore */
'mi-&#xe929;', /* restore_page */
'mi-&#xe0d1;', /* ring_volume */
'mi-&#xe8b4;', /* room */
'mi-&#xeb49;', /* room_service */
'mi-&#xe418;', /* rotate_90_degrees_ccw */
'mi-&#xe419;', /* rotate_left */
'mi-&#xe41a;', /* rotate_right */
'mi-&#xe920;', /* rounded_corner */
'mi-&#xe328;', /* router */
'mi-&#xe921;', /* rowing */
'mi-&#xe0e5;', /* rss_feed */
'mi-&#xe642;', /* rv_hookup */
'mi-&#xe562;', /* satellite */
'mi-&#xe161;', /* save */
'mi-&#xe329;', /* scanner */
'mi-&#xe8b5;', /* schedule */
'mi-&#xe80c;', /* school */
'mi-&#xe1be;', /* screen_lock_landscape */
'mi-&#xe1bf;', /* screen_lock_portrait */
'mi-&#xe1c0;', /* screen_lock_rotation */
'mi-&#xe1c1;', /* screen_rotation */
'mi-&#xe0e2;', /* screen_share */
'mi-&#xe623;', /* sd_card */
'mi-&#xe1c2;', /* sd_storage */
'mi-&#xe8b6;', /* search */
'mi-&#xe32a;', /* security */
'mi-&#xe162;', /* select_all */
'mi-&#xe163;', /* send */
'mi-&#xe811;', /* sentiment_dissatisfied */
'mi-&#xe812;', /* sentiment_neutral */
'mi-&#xe813;', /* sentiment_satisfied */
'mi-&#xe814;', /* sentiment_very_dissatisfied */
'mi-&#xe815;', /* sentiment_very_satisfied */
'mi-&#xe8b8;', /* settings */
'mi-&#xe8b9;', /* settings_applications */
'mi-&#xe8ba;', /* settings_backup_restore */
'mi-&#xe8bb;', /* settings_bluetooth */
'mi-&#xe8bd;', /* settings_brightness */
'mi-&#xe8bc;', /* settings_cell */
'mi-&#xe8be;', /* settings_ethernet */
'mi-&#xe8bf;', /* settings_input_antenna */
'mi-&#xe8c0;', /* settings_input_component */
'mi-&#xe8c1;', /* settings_input_composite */
'mi-&#xe8c2;', /* settings_input_hdmi */
'mi-&#xe8c3;', /* settings_input_svideo */
'mi-&#xe8c4;', /* settings_overscan */
'mi-&#xe8c5;', /* settings_phone */
'mi-&#xe8c6;', /* settings_power */
'mi-&#xe8c7;', /* settings_remote */
'mi-&#xe1c3;', /* settings_system_daydream */
'mi-&#xe8c8;', /* settings_voice */
'mi-&#xe80d;', /* share */
'mi-&#xe8c9;', /* shop */
'mi-&#xe8ca;', /* shop_two */
'mi-&#xe8cb;', /* shopping_basket */
'mi-&#xe8cc;', /* shopping_cart */
'mi-&#xe261;', /* short_text */
'mi-&#xe6e1;', /* show_chart */
'mi-&#xe043;', /* shuffle */
'mi-&#xe1c8;', /* signal_cellular_4_bar */
'mi-&#xe1cd;', /* signal_cellular_connected_no_internet_4_bar */
'mi-&#xe1ce;', /* signal_cellular_no_sim */
'mi-&#xe1cf;', /* signal_cellular_null */
'mi-&#xe1d0;', /* signal_cellular_off */
'mi-&#xe1d8;', /* signal_wifi_4_bar */
'mi-&#xe1d9;', /* signal_wifi_4_bar_lock */
'mi-&#xe1da;', /* signal_wifi_off */
'mi-&#xe32b;', /* sim_card */
'mi-&#xe624;', /* sim_card_alert */
'mi-&#xe044;', /* skip_next */
'mi-&#xe045;', /* skip_previous */
'mi-&#xe41b;', /* slideshow */
'mi-&#xe068;', /* slow_motion_video */
'mi-&#xe32c;', /* smartphone */
'mi-&#xeb4a;', /* smoke_free */
'mi-&#xeb4b;', /* smoking_rooms */
'mi-&#xe625;', /* sms */
'mi-&#xe626;', /* sms_failed */
'mi-&#xe046;', /* snooze */
'mi-&#xe164;', /* sort */
'mi-&#xe053;', /* sort_by_alpha */
'mi-&#xeb4c;', /* spa */
'mi-&#xe256;', /* space_bar */
'mi-&#xe32d;', /* speaker */
'mi-&#xe32e;', /* speaker_group */
'mi-&#xe8cd;', /* speaker_notes */
'mi-&#xe92a;', /* speaker_notes_off */
'mi-&#xe0d2;', /* speaker_phone */
'mi-&#xe8ce;', /* spellcheck */
'mi-&#xe838;', /* star */
'mi-&#xe83a;', /* star_border */
'mi-&#xe839;', /* star_half */
'mi-&#xe8d0;', /* stars */
'mi-&#xe0d3;', /* stay_current_landscape */
'mi-&#xe0d4;', /* stay_current_portrait */
'mi-&#xe0d5;', /* stay_primary_landscape */
'mi-&#xe0d6;', /* stay_primary_portrait */
'mi-&#xe047;', /* stop */
'mi-&#xe0e3;', /* stop_screen_share */
'mi-&#xe1db;', /* storage */
'mi-&#xe8d1;', /* store */
'mi-&#xe563;', /* store_mall_directory */
'mi-&#xe41c;', /* straighten */
'mi-&#xe56e;', /* streetview */
'mi-&#xe257;', /* strikethrough_s */
'mi-&#xe41d;', /* style */
'mi-&#xe5d9;', /* subdirectory_arrow_left */
'mi-&#xe5da;', /* subdirectory_arrow_right */
'mi-&#xe8d2;', /* subject */
'mi-&#xe064;', /* subscriptions */
'mi-&#xe048;', /* subtitles */
'mi-&#xe56f;', /* subway */
'mi-&#xe8d3;', /* supervisor_account */
'mi-&#xe049;', /* surround_sound */
'mi-&#xe0d7;', /* swap_calls */
'mi-&#xe8d4;', /* swap_horiz */
'mi-&#xe8d5;', /* swap_vert */
'mi-&#xe8d6;', /* swap_vertical_circle */
'mi-&#xe41e;', /* switch_camera */
'mi-&#xe41f;', /* switch_video */
'mi-&#xe627;', /* sync */
'mi-&#xe628;', /* sync_disabled */
'mi-&#xe629;', /* sync_problem */
'mi-&#xe62a;', /* system_update */
'mi-&#xe8d7;', /* system_update_alt */
'mi-&#xe8d8;', /* tab */
'mi-&#xe8d9;', /* tab_unselected */
'mi-&#xe32f;', /* tablet */
'mi-&#xe330;', /* tablet_android */
'mi-&#xe331;', /* tablet_mac */
'mi-&#xe420;', /* tag_faces */
'mi-&#xe62b;', /* tap_and_play */
'mi-&#xe564;', /* terrain */
'mi-&#xe262;', /* text_fields */
'mi-&#xe165;', /* text_format */
'mi-&#xe0d8;', /* textsms */
'mi-&#xe421;', /* texture */
'mi-&#xe8da;', /* theaters */
'mi-&#xe8db;', /* thumb_down */
'mi-&#xe8dc;', /* thumb_up */
'mi-&#xe8dd;', /* thumbs_up_down */
'mi-&#xe62c;', /* time_to_leave */
'mi-&#xe422;', /* timelapse */
'mi-&#xe922;', /* timeline */
'mi-&#xe425;', /* timer */
'mi-&#xe423;', /* timer_10 */
'mi-&#xe424;', /* timer_3 */
'mi-&#xe426;', /* timer_off */
'mi-&#xe264;', /* title */
'mi-&#xe8de;', /* toc */
'mi-&#xe8df;', /* today */
'mi-&#xe8e0;', /* toll */
'mi-&#xe427;', /* tonality */
'mi-&#xe913;', /* touch_app */
'mi-&#xe332;', /* toys */
'mi-&#xe8e1;', /* track_changes */
'mi-&#xe565;', /* traffic */
'mi-&#xe570;', /* train */
'mi-&#xe571;', /* tram */
'mi-&#xe572;', /* transfer_within_a_station */
'mi-&#xe428;', /* transform */
'mi-&#xe8e2;', /* translate */
'mi-&#xe8e3;', /* trending_down */
'mi-&#xe8e4;', /* trending_flat */
'mi-&#xe8e5;', /* trending_up */
'mi-&#xe429;', /* tune */
'mi-&#xe8e6;', /* turned_in */
'mi-&#xe8e7;', /* turned_in_not */
'mi-&#xe333;', /* tv */
'mi-&#xe169;', /* unarchive */
'mi-&#xe166;', /* undo */
'mi-&#xe5d6;', /* unfold_less */
'mi-&#xe5d7;', /* unfold_more */
'mi-&#xe923;', /* update */
'mi-&#xe1e0;', /* usb */
'mi-&#xe8e8;', /* verified_user */
'mi-&#xe258;', /* vertical_align_bottom */
'mi-&#xe259;', /* vertical_align_center */
'mi-&#xe25a;', /* vertical_align_top */
'mi-&#xe62d;', /* vibration */
'mi-&#xe070;', /* video_call */
'mi-&#xe071;', /* video_label */
'mi-&#xe04a;', /* video_library */
'mi-&#xe04b;', /* videocam */
'mi-&#xe04c;', /* videocam_off */
'mi-&#xe338;', /* videogame_asset */
'mi-&#xe8e9;', /* view_agenda */
'mi-&#xe8ea;', /* view_array */
'mi-&#xe8eb;', /* view_carousel */
'mi-&#xe8ec;', /* view_column */
'mi-&#xe42a;', /* view_comfy */
'mi-&#xe42b;', /* view_compact */
'mi-&#xe8ed;', /* view_day */
'mi-&#xe8ee;', /* view_headline */
'mi-&#xe8ef;', /* view_list */
'mi-&#xe8f0;', /* view_module */
'mi-&#xe8f1;', /* view_quilt */
'mi-&#xe8f2;', /* view_stream */
'mi-&#xe8f3;', /* view_week */
'mi-&#xe435;', /* vignette */
'mi-&#xe8f4;', /* visibility */
'mi-&#xe8f5;', /* visibility_off */
'mi-&#xe62e;', /* voice_chat */
'mi-&#xe0d9;', /* voicemail */
'mi-&#xe04d;', /* volume_down */
'mi-&#xe04e;', /* volume_mute */
'mi-&#xe04f;', /* volume_off */
'mi-&#xe050;', /* volume_up */
'mi-&#xe0da;', /* vpn_key */
'mi-&#xe62f;', /* vpn_lock */
'mi-&#xe1bc;', /* wallpaper */
'mi-&#xe002;', /* warning */
'mi-&#xe334;', /* watch */
'mi-&#xe924;', /* watch_later */
'mi-&#xe42c;', /* wb_auto */
'mi-&#xe42d;', /* wb_cloudy */
'mi-&#xe42e;', /* wb_incandescent */
'mi-&#xe436;', /* wb_iridescent */
'mi-&#xe430;', /* wb_sunny */
'mi-&#xe63d;', /* wc */
'mi-&#xe051;', /* web */
'mi-&#xe069;', /* web_asset */
'mi-&#xe16b;', /* weekend */
'mi-&#xe80e;', /* whatshot */
'mi-&#xe1bd;', /* widgets */
'mi-&#xe63e;', /* wifi */
'mi-&#xe1e1;', /* wifi_lock */
'mi-&#xe1e2;', /* wifi_tethering */
'mi-&#xe8f9;', /* work */
'mi-&#xe25b;', /* wrap_text */
'mi-&#xe8fa;', /* youtube_searched_for */
'mi-&#xe8ff;', /* zoom_in */
'mi-&#xe900;', /* zoom_out */
'mi-&#xe56b;', /* zoom_out_map */
);
		
	foreach( $material_icons as $icon ) :
		$icons[] = $icon;
	endforeach;
	
    return $icons;
}
add_filter('et_pb_font_icon_symbols', 'materialicons_icons');

/**
 * Overwrites the same function in Divi's functions.php file. 
 * Identify the new icons in the divi builder so we can handle 
 * them accordingly.
 *
 * @since    1.0.0
 */
if ( ! function_exists( 'et_pb_get_font_icon_list_items' ) ) {
	
	function et_pb_get_font_icon_list_items() {

		$output = '';
	
		$symbols = et_pb_get_font_icon_symbols();
			
		foreach ( $symbols as $symbol ) {
		
			$icon_checker = substr( $symbol, 0, 3 );

			// if Divi Font Awesome plugin is in use, still render those icons
			if( $icon_checker === 'fa-' ) :
				$symbol_parts = explode( '-', $symbol );
				$output .= sprintf( '<li data-icon=\'%1$s\' class="fa fa-fw fa-divi-fontawesome-builder"></li>', esc_attr( $symbol_parts[1] ) );
			// and of course, for our Material Icons, add the appropriate classes too
			elseif( $icon_checker === 'mi-' ) :
				$symbol_parts = explode( '-', $symbol );
				$output .= sprintf( '<li data-icon=\'%1$s\' class="mi mi-divi-materialicons-builder"></li>', esc_attr( $symbol_parts[1] ) );
			// otherwise, do the normal Divi output of the list item wrapper
			else :
				$output .= sprintf( '<li data-icon=\'%1$s\'></li>', esc_attr( $symbol ) );
			endif;
		}

		return $output;
	}
}

add_filter( 'plugin_action_links', 'fs_dmi_add_action_plugin', 10, 5 );

add_action( 'admin_menu', 'fs_dmi_admin_menu' );

add_action( 'wp_enqueue_scripts', 'fs_dmi_public_script' );

add_action( 'wp_enqueue_scripts', 'fs_dmi_materialicons' );

add_action( 'admin_enqueue_scripts', 'fs_dmi_materialicons' );